# -*- coding: utf-8 -*-
"""ML_LAB_03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ykMbRDZoInh7LKqu11So8c8_BP7lVKsw

Name:Harsh Pandit

Roll No:H036

Program : Mechatronics

Division:H

Batch: H1

Date of Experiment: 23/12/2021

Date of Submission: 8/1/2022
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

df=pd.read_excel('Lab 3.xlsx')#read the excel file
df

df['Income']=df['Income'].replace('..',value=float(00)) #replaced '..' with 00
mean=df[df['Income']!=0].mean() #took mean income
df['Income']=df['Income'].replace(00,value=float(mean['Income'])) #replaced '..' with mean income
x=df[['Income']]  #assigned x value as income
y=df[['Satisfaction']]  #assigned y value as satisfaction
model= LinearRegression()
model.fit(x,y) #fit the model in our data

y_pred=model.predict(x)   #plotted the predicted value as well as given value
plt.scatter(x,y,color='black')
plt.plot(x,y_pred,'red')

y_mean=df['Satisfaction'].mean()
df['yi-y_mean']=y-y_mean #made a column of yi-y_mean
x_mean=df['Income'].mean()
df['ypred-y_mean']=y_pred-y_mean   #made a column of ypred-y_mean
r_square=model.score(x,y)
print("r squared is:",r_square)

SSR=(df['ypred-y_mean']**2).sum() #found SSR value
print("SSR is : ",SSR)
SST=(df['yi-y_mean']**2).sum() #found SST value
print("SST is : ",SST)
SSE=SST-SSR   #found SSE value
print("SSE is : ",SSE)

b0=model.intercept_#intercept
b1=model.coef_#slope
print('The equation is',b0,'+',b1,'x')#equation of regression line

x=sm.add_constant(x)#add constants to x
mod=sm.OLS(y,x)#create the model
res=mod.fit()#fit the model
print(res.summary())#print the results

"""Conclusion: In this experiment we found the r squared value using two methods. First by LinearRegression package and second by statsmodel package. We plotted the graph for given data and the equation for regression line. We also cleaned the data before performing linear regression opression."""