# -*- coding: utf-8 -*-
"""ML_LAB_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R5KUHX7VypKUXf-vXu5MBbHNnNLWdj6_

Name:Harsh Pandit

Roll No:H036

Program : Mechatronics

Division:H

Batch: H1

Date of Experiment: 9/12/2021

Date of Submission: Grade :16/12/2021
"""

import numpy as np

temp_list_in_c=[0,12,23,45,56]
temp_list_in_f=[]
for i in temp_list_in_c:
  temp_list_in_f.append(i*(9/5)+32)
print(temp_list_in_f)

temp_list_in_c=np.array([0,12,23,45,56])
temp_list_in_f=temp_list_in_c*(9/5)+32
print(temp_list_in_f)
import matplotlib.pyplot as plt
plt.plot(temp_list_in_c,temp_list_in_f,'db')# plt.plot(x_cood,y_cood), plots the points

m=np.array(([1,2,3],[4,5,6]))
print("The original array is: ")
print(m)
print("The flipped array is: ")
n=np.fliplr(m) #flips colums order
print(n)

m=np.array(([1,2,3],[4,5,6]))
print("The original array is: ")
print(m)
print("The flipped array is: ")
n=np.flipud(m) #flips the row order
print(n)

import pandas as pd
df=pd.read_csv('/content/StudentsPerformance.csv')#reads the csv file as data frame, in () we have to give file link
print(df.head(10))#prints data frame from head/top

print(df.tail(10))#prints data frame from tail/bottom

print(df.shape)#prints rows and columns

df.axes#prints name of columns

df.ndim#prints name of columns

df['reading score'].sum()#sum of elements in particular column

df['writing score'].mean()#mean of elements in particular column

df['math score'].describe()

df.iloc[10]#gives data of 10th index location

df.loc[7,'math score']

plt.bar((df['parental level of education']),(df['math score']))

plt.bar(df['gender'],df['math score'],width=0.1,color='r')

plt.bar(df['gender'],df['writing score'],width=0.1,color='g')

plt.bar(df['gender'],df['reading score'],width=0.1,color='black')

"""Conclusion: We understood the basics of matlpot and numpy. We also plotted bargraphs using
matplot and numpy. We also worked with the basics of panda. We also worked with particular
columns and various functions associated with it. We also saw how to read csv file.
"""