# -*- coding: utf-8 -*-
"""ML_LAB_06b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M2PnZWWuic6bKN8FYOfdxESbSqGUnY9l
"""

import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import Normalizer
from statistics import mode

df=pd.read_csv("Iris.csv")
df['Species']=df['Species'].replace(('Iris-setosa','Iris-versicolor','Iris-virginica'),value=(1,2,3))
df=df.drop('Id',axis=1)
df['Index']=0
df.head()

for i in range(0,len(df)):
  df['Index'].iloc[i]=i
df.head()

y=df['Species']
x=df.drop(('Species'),axis=1)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

mod=Normalizer().fit(x_train)
norm_x_train=mod.transform(x_train)
norm_x_test=mod.transform(x_test)

df1=pd.DataFrame()
df1['y_train']=y_test

dist=[]
for i in norm_x_test:
  value=[]
  for j in norm_x_train:
    value.append((abs(i-j)))
  dist.append(sum(value))

dist

st#df2=df2.sort_values(by='distance',ascending=True)
a=[1,2,3,2,1,2,1,1,1,1,1]
mode(a)

a={}
for c in range (0,10):
  mn=[]
  for b in range(1,3):
    mn.append(b)
  a[c]=mn
a