# -*- coding: utf-8 -*-
"""ML_LAB_07a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mAlEw-BQ97JFd5RD75nejTfuONv-MWJX

Name:Harsh Pandit

Roll No:H036

Program : Mechatronics

Division:H

Batch: H1

Date of Experiment: 3/02/2022

Date of Submission: 15/02/2022
"""

#importing all relevant libraries
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

#reading the file
df=pd.read_csv('play_tennis.csv')
df.head()

#replacing all categorical variables
for i in range (0,len(df)+1):
  df['day'].loc[i]=i+1
df['outlook']=df['outlook'].replace(('Rain','Overcast','Sunny'),value=(1,2,3))
df['temp']=df['temp'].replace(('Cool','Mild','Hot'),value=(1,2,3))
df['humidity']=df['humidity'].replace(('Normal','High'),value=(0,1))
df['wind']=df['wind'].replace(('Weak','Strong'),value=(0,1))
df['play']=df['play'].replace(('No','Yes'),value=(0,1))

df

#defining y and x
y=df['play']
x=df.drop('play',axis=1)
#splitting the data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)#split the data in test and train

#defining the model
model=GaussianNB()
model.fit(x_train, y_train)
#calculationg y predicted
y_pred=model.predict(x_test)

df1=pd.DataFrame()
df1['y']=y_test
df1['y_pred']=y_pred

df1

#finding out the error
error=mean_squared_error(y_pred,y_test)
print('The error is: ',error)

"""Conclusion: Hence the gaussian bayes algorithm was implemented succesfully. The error was found out  to be 0.333333."""