# -*- coding: utf-8 -*-
"""ML_LAB_10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f09FXJ7OrcMAdil-MMSiZDG-_PhJGXI1

Name:Harsh Pandit

Roll No:H036

Program : Mechatronics

Division:H

Batch: H1

Date of Experiment: 3/03/2022

Date of Submission: 13/03/2022
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
#https://www.kaggle.com/shivavashishtha/shark-tank-india-dataset

#from sklearn.model_selection import train_test_split
#from sklearn.naive_bayes import GaussianNB
#from sklearn.metrics import confusion_matrix, accuracy_score, roc_curve,roc_auc_score
#from sklearn.linear_model import LogisticRegression
#from sklearn.tree import DecisionTreeClassifier

df=pd.read_csv('Shark Tank India.csv')
df.describe()

corr = df.corr()
corr

sns.heatmap(corr)

df.columns

df=df.drop(['AshneerGrover_present', 'AnupamMittal_present',
       'AmanGupta_present', 'NamitaThapar_present', 'VineetaSingh_present',
       'PeyushBansal_present', 'GhazalAlagh_present', 'AshneerGrover_deal',
       'AnupamMittal_deal', 'AmanGupta_deal', 'NamitaThapar_deal',
       'VineetaSingh_deal', 'PeyushBansal_deal', 'GhazalAlagh_deal','Episode'],axis=1)

corr = df.corr()
corr

sns.heatmap(corr)

df=df.dropna()

corr = df.corr()
corr

sns.heatmap(corr)

df=df.drop('Receive_Offer',axis=1)
corr=df.corr()
sns.heatmap(corr)

df=df.drop('Reject_Offer',axis=1)

corr=df.corr()
s=sns.heatmap(corr,annot=True,annot_kws={'size': 5},cmap='Greys')
plt.show()

df=df.drop('Number of Sharks invested',axis=1)

corr=df.corr()

s=sns.heatmap(corr,annot=True,annot_kws={'size': 5},cmap='Blacks')
plt.show()

s=sns.heatmap(corr,annot=True,annot_kws={'size': 5},cmap='bone')
plt.show()

df=df.drop('No of male presenters',axis=1)
corr=df.corr()
s=sns.heatmap(corr,annot=True,annot_kws={'size': 5},cmap='bone')
plt.show()

